server:
  compression:
    enabled: true
  port: 8088

spring:
  application:
    name: 'cactus'
  jackson:
    timeZone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    parser:
      allow-single-quotes: true
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
  cache:
    type: redis
    redis:
      time-to-live: PT15M
      key-prefix: '@project.name@'
      use-key-prefix: true
      cache-null-values: false
  datasource:
    #本地数据库
    cloudwise:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&autoReconnect=true&useSSL=false
      username: root
      password: root
      connectionTimeOut: 10000
      type: com.alibaba.druid.pool.DruidDataSource
      filter: stat,wall,slf4j
      useGlobalDataSourceStat: true
    #透视宝
    tsb:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test2?useUnicode=true&autoReconnect=true&characterEncoding=utf8&connectionCollation=utf8_general_ci
      username: root
      password: root
      connectionTimeOut: 10000
      type: com.alibaba.druid.pool.DruidDataSource
      filter: stat,wall,slf4j
      useGlobalDataSourceStat: true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      transaction-isolation: 4 # java.sql.Connection.TRANSACTION_REPEATABLE_READ

#    dynamic:
#      primary: primary #设置默认的数据源或者数据源组,默认值即为master
#      strict: false
#      name: hikariDataSource
#      datasource:
#        primary:
#          url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&autoReconnect=true&useSSL=false
#          username: root
#          password: root
#        secondary:
#          url: jdbc:mysql://127.0.0.1:3306/test2?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
#          username: root
#          password: root
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      connection-timeout: 30000
#      transaction-isolation: 4 # java.sql.Connection.TRANSACTION_REPEATABLE_READ
  # redis 集群配置
  #  redis:
  #    database: 0
  #    password: 'Cloud@#$%123'
  #    port: 6379
  #    cluster:
  #      nodes:
  #        - cluster-101:6379
  #        - cluster-102:6379
  #        - cluster-103:6379
  #        - cluster-104:6379
  #        - cluster-105:6379
  #        - cluster-106:6379
  #    lettuce:
  #      pool:
  #        max-active: 10
  #        max-idle: 8
  #        min-idle: 0
  #      cluster:
  #        refresh:
  #          period: PT60S
  # redis 单机配置
#  redis:
#    database: 0
#    host: 192.168.175.145
#    port: 6379
#    password:
#    timeout: 1000
#    pool:
#      max-active: 20
#      max-wait: -1
#      max-idle: 10
#      min-idle: 1
#  kafka:
#    bootstrap-servers: 127.0.0.1:9092
#    listener:
#      type: batch
#    consumer:
#      max-poll-records: 1000
#      properties:
#        max:
#          partition:
#            fetch:
#              bytes: 30485760 #拉取partition的数据大小
#    producer:
#      batch-size: 1000 #批量提交的记录
#      buffer-memory: 5242880 #生产端缓冲区大小
#      properties:
#        linger:
#          ms: 1000 #提交延迟
  mvc:
    throw-exception-if-no-handler-found: true
  groovy:
    template:
      check-template-location: false
  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      client:
        url: http://localhost:${server.port}

#mybatis-plus:
#  mapper-locations: classpath:mapper/**/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    default-statement-timeout: 3 # 查询超时间,单位秒,不设置则无线等待
#    default-fetch-size: 100
#    map-underscore-to-camel-case: true
#  type-aliases-package: com.cloudwise.cactus_demo.pojo.*

#springfox:
#  documentation:
#    swagger-ui:
#      enabled: true
#    auto-startup: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

#swagger:
#  info:
#    name: ${spring.application.name}
#    group: 'com.cloudwise'
#    version: '1.0'
#    profile: ${spring.profiles.active}
#    description: '@project.description@'
#    contact:
#      name: Cactus
#      mail: cactus@cloudwise.com

logging:
  level:
    com.cloudwise.cactus: debug
  file:
    name: logs/info.log

job:
  baseSleepTimeMilliseconds: 1000
  maxSleepTimeMilliseconds: 3000
  sessionTimeoutMilliseconds: 60000
  connectionTimeoutMilliseconds: 60000
  maxRetries: 3
  zkServerList: 127.0.0.1:2181
  namespace: rtp-core-job
  job1Shards: 1
  job1Cron: 0/5 * * * * ?
  job2Shards: 2
  job2Cron: 0/10 * * * * ?